# Generated by Django 6.0.2 on 2026-03-27 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assistantchat',
            new_name='assistant_a_user_id_6b2269_idx',
            old_name='assistantc_user_id_0c4a7e_idx',
        ),
        migrations.RenameIndex(
            model_name='assistantchat',
            new_name='assistant_a_user_id_98d976_idx',
            old_name='assistantc_user_id_83c5a3_idx',
        ),
        migrations.RenameIndex(
            model_name='assistantturn',
            new_name='assistant_a_chat_id_3076e0_idx',
            old_name='assistantt_chat_id_5f54a9_idx',
        ),
    ]
