services:
  db:
    image: postgres:17-alpine
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  cache:
    image: redis:7.2.4
    restart: always
    volumes:
      - ./data/cache:/data
  web:
    build: .
    command: ["./wait-for-it.sh", "db:5432", "--",
            "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    volumes:
      -  .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=edu.settings.prod
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - REDIS_URL=${REDIS_URL:-redis://cache:6379/1}
    depends_on:
      - db
      - cache
  nginx:
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    environment:
      - SERVER_NAME=${SERVER_NAME:-educaproject.com}
    ports:
      - "80:80"
      - "443:443"
  daphne:
    build: .
    working_dir: /code/edu/
    command: ["../wait-for-it.sh", "db:5432", "--",
            "daphne", "-b", "0.0.0.0", "-p", "9001",
            "edu.asgi:application"]
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=edu.settings.prod
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - REDIS_URL=${REDIS_URL:-redis://cache:6379/1}
    depends_on:
      - db
      - cache
  worker:
    build: .
    working_dir: /code/edu/
    command: ["../wait-for-it.sh", "db:5432", "--",
            "python", "manage.py", "learning_insights_worker",
            "--settings=edu.settings.prod"]
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=edu.settings.prod
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - REDIS_URL=${REDIS_URL:-redis://cache:6379/1}
    depends_on:
      - db
      - cache
