# Generated by Codex on 2026-02-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_students"),
        ("chat", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["course", "id"], name="chat_messag_course__68eb34_idx"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["course", "sent_on"],
                name="chat_messag_course__0f4fac_idx",
            ),
        ),
        migrations.CreateModel(
            name="CourseReadState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_read_message_id", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_read_states",
                        to="courses.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_read_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "course"],
                        name="chat_course_user_id_6159fc_idx",
                    ),
                    models.Index(
                        fields=["course", "user"],
                        name="chat_course_course__ed14e0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "course"),
                        name="uniq_chat_read_state_user_course",
                    )
                ],
            },
        ),
    ]
