# Generated by Django 6.0.2 on 2026-02-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_coursereadstate_message_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='coursereadstate',
            new_name='chat_course_user_id_1a9955_idx',
            old_name='chat_course_user_id_6159fc_idx',
        ),
        migrations.RenameIndex(
            model_name='coursereadstate',
            new_name='chat_course_course__8a00f7_idx',
            old_name='chat_course_course__ed14e0_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_course__fce036_idx',
            old_name='chat_messag_course__68eb34_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_course__6d76dc_idx',
            old_name='chat_messag_course__0f4fac_idx',
        ),
    ]
