# Generated by Django 6.0.2 on 2026-04-19 13:53

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0009_expand_filefield_paths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('week_start_day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0)),
                ('daily_enabled', models.BooleanField(default=True)),
                ('weekly_enabled', models.BooleanField(default=True)),
                ('daily_achievement_enabled', models.BooleanField(default=True)),
                ('weekly_achievement_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('daily_time', models.TimeField(default=datetime.time(8, 0))),
                ('weekly_time', models.TimeField(default=datetime.time(8, 0))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_insights_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification preference',
                'verbose_name_plural': 'Notification preferences',
            },
        ),
        migrations.CreateModel(
            name='DailyCourseStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('module_seconds', models.PositiveIntegerField(default=0)),
                ('content_active_seconds', models.PositiveIntegerField(default=0)),
                ('completed_content_count', models.PositiveIntegerField(default=0)),
                ('session_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_insight_stats', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_course_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['user', 'date'], name='li_dcs_user_date_idx'), models.Index(fields=['user', 'course', 'date'], name='li_dcs_user_course_date_idx')],
                'unique_together': {('user', 'course', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailySiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('ping_count', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_site_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-id'],
                'indexes': [models.Index(fields=['user', 'date'], name='li_dss_user_date_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('long_term', 'Long term')], default='weekly', max_length=16)),
                ('target_type', models.CharField(choices=[('minutes', 'Minutes'), ('tasks', 'Tasks'), ('completion_percent', 'Completion percent')], default='minutes', max_length=24)),
                ('target_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=12)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('overdue', 'Overdue')], default='not_started', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_goals', to='courses.course')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='learning_insights.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', '-created'],
                'indexes': [models.Index(fields=['user', 'period_type', 'status'], name='li_goal_user_period_status_idx'), models.Index(fields=['user', 'start_date', 'due_date'], name='li_goal_user_dates_idx'), models.Index(fields=['user', 'course'], name='li_goal_user_course_idx')],
            },
        ),
        migrations.CreateModel(
            name='InsightNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('daily_start', 'Daily start'), ('weekly_start', 'Weekly start'), ('daily_achievement', 'Daily achievement'), ('weekly_achievement', 'Weekly achievement'), ('goal_due', 'Goal due')], max_length=32)),
                ('channel', models.CharField(choices=[('in_app', 'In-app')], default='in_app', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=120)),
                ('scheduled_for', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_for', '-id'],
                'indexes': [models.Index(fields=['user', 'channel', 'scheduled_for'], name='li_notif_user_chan_sched_idx'), models.Index(fields=['user', 'read_at'], name='li_notif_user_read_idx'), models.Index(fields=['user', 'category'], name='li_notif_user_category_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'channel', 'dedupe_key'), name='li_notif_unique_dedupe_key')],
            },
        ),
        migrations.CreateModel(
            name='StudyTimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds_delta', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('module', 'Module')], default='module', max_length=16)),
                ('session_end_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('local_date', models.DateField()),
                ('local_hour', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_time_events', to='courses.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_time_events', to='courses.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_time_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session_end_at', '-id'],
                'indexes': [models.Index(fields=['user', 'local_date'], name='li_evt_user_date_idx'), models.Index(fields=['user', 'course', 'local_date'], name='li_evt_user_course_date_idx'), models.Index(fields=['session_end_at'], name='li_evt_end_idx')],
            },
        ),
    ]
