# Generated by Django 6.0.2 on 2026-04-19 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_insights', '0002_telegramsubscription_notificationqueue_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='telegram_critical_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='telegram_daily_summary_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='telegram_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='telegram_weekly_review_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AIPlanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('weekly_plan', 'Weekly plan'), ('daily_review', 'Daily review'), ('weekly_review', 'Weekly review'), ('improvement', 'Improvement suggestions'), ('recovery', 'Recovery suggestions')], default='weekly_plan', max_length=24)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('long_term', 'Long term')], default='weekly', max_length=16)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_payload', models.JSONField(blank=True, default=dict)),
                ('edited_payload', models.JSONField(blank=True, default=dict)),
                ('summary_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_plan_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'kind', 'created_at'], name='li_air_user_kind_idx'), models.Index(fields=['status', 'created_at'], name='li_air_status_date_idx')],
            },
        ),
    ]
