# Generated by Django 6.0.2 on 2026-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_insights', '0004_delete_notificationqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiplanrun',
            name='kind',
            field=models.CharField(choices=[('prompt_plan', 'Prompt plan'), ('weekly_plan', 'Weekly plan'), ('daily_plan', 'Daily plan'), ('daily_review', 'Daily review'), ('weekly_review', 'Weekly review'), ('improvement', 'Improvement suggestions'), ('recovery', 'Recovery suggestions')], default='prompt_plan', max_length=24),
        ),
    ]
