# Generated by Django 6.0.2 on 2026-04-21 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_insights', '0005_alter_aiplanrun_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='telegram_critical_alerts_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='telegram_daily_summary_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='telegram_weekly_review_enabled',
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='telegram_evening_summary_end',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='telegram_evening_summary_start',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='telegram_morning_summary_end',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='telegram_morning_summary_start',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
