# Generated by Django 6.0.2 on 2026-04-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_insights', '0006_remove_notificationpreference_telegram_critical_alerts_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightnotification',
            name='telegram_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
