# Generated by Django 6.0.2 on 2026-03-07 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_module_progress_percent(apps, schema_editor):
    ModuleProgress = apps.get_model("students", "ModuleProgress")
    ModuleProgress.objects.filter(completed=True).update(progress_percent=100.0)
    ModuleProgress.objects.filter(completed=False).update(progress_percent=0.0)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_file_pdf_index_error_file_pdf_index_status_and_more'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprogress',
            name='progress_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='ContentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF')], max_length=12)),
                ('progress_percent', models.FloatField(default=0.0)),
                ('completed', models.BooleanField(default=False)),
                ('seconds_spent', models.PositiveIntegerField(default=0)),
                ('last_position', models.JSONField(blank=True, default=dict)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='courses.content')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to='courses.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to='courses.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.RunPython(
            backfill_module_progress_percent,
            migrations.RunPython.noop,
        ),
    ]
