# Generated by Django 6.0.2 on 2026-04-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_courseprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentprogress',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF'), ('video', 'Video')], max_length=12),
        ),
    ]
