# Generated by Django 6.0.2 on 2026-03-07

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F, Func


def _normalize_whitespace(value):
    return " ".join((value or "").split())


def backfill_course_search_index(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    Module = apps.get_model("courses", "Module")
    CourseSearchIndex = apps.get_model("courses", "CourseSearchIndex")

    module_map = {}
    for course_id, title, description in Module.objects.values_list(
        "course_id", "title", "description"
    ):
        module_map.setdefault(course_id, []).append(_normalize_whitespace(title))
        module_map.setdefault(course_id, []).append(_normalize_whitespace(description))

    rows = []
    for course in Course.objects.select_related("subject").all().iterator():
        parts = [
            _normalize_whitespace(course.title),
            _normalize_whitespace(course.overview),
            _normalize_whitespace(course.subject.title if course.subject_id else ""),
        ]
        parts.extend(p for p in module_map.get(course.id, []) if p)
        rows.append(
            CourseSearchIndex(
                course_id=course.id,
                document="\n".join(p for p in parts if p),
            )
        )

    if rows:
        CourseSearchIndex.objects.bulk_create(rows, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_students"),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        django.contrib.postgres.operations.UnaccentExtension(),
        migrations.CreateModel(
            name="CourseSearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.TextField(blank=True, default="")),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_index",
                        to="courses.course",
                    ),
                ),
            ],
            options={},
        ),
        migrations.RunSQL(
            sql=(
                "CREATE OR REPLACE FUNCTION immutable_unaccent(text) "
                "RETURNS text "
                "LANGUAGE sql IMMUTABLE PARALLEL SAFE "
                "AS $$ SELECT public.unaccent($1); $$;"
            ),
            reverse_sql="DROP FUNCTION IF EXISTS immutable_unaccent(text);",
        ),
        migrations.AddIndex(
            model_name="coursesearchindex",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    Func(
                        F("document"),
                        function="immutable_unaccent",
                        output_field=models.TextField(),
                    ),
                    config="simple",
                ),
                name="course_idx_doc_tsv_gin",
            ),
        ),
        migrations.AddIndex(
            model_name="coursesearchindex",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["document"],
                name="course_idx_doc_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.RunPython(
            backfill_course_search_index,
            migrations.RunPython.noop,
        ),
    ]
