# Generated by Django 6.0.2 on 2026-03-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursesearchindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='pdf_index_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='file',
            name='pdf_index_status',
            field=models.CharField(default='pending', max_length=24),
        ),
        migrations.AddField(
            model_name='file',
            name='pdf_indexed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='pdf_page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='pdf_text_index',
            field=models.TextField(blank=True, default=''),
        ),
    ]
