# Generated by Django 6.0.2 on 2026-03-14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F, Func


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_file_pdf_index_error_file_pdf_index_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentSearchEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=24)),
                ("item_title", models.CharField(blank=True, default="", max_length=250)),
                ("document", models.TextField(blank=True, default="")),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_entries",
                        to="courses.content",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_search_entries",
                        to="courses.course",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_search_entries",
                        to="courses.module",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="contentsearchentry",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    Func(
                        F("document"),
                        function="immutable_unaccent",
                        output_field=models.TextField(),
                    ),
                    config="simple",
                ),
                name="content_idx_doc_tsv_gin",
            ),
        ),
        migrations.AddIndex(
            model_name="contentsearchentry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["document"],
                name="content_idx_doc_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="contentsearchentry",
            index=models.Index(
                fields=["course", "module", "content"],
                name="content_idx_course_module",
            ),
        ),
        migrations.AddIndex(
            model_name="contentsearchentry",
            index=models.Index(
                fields=["kind", "page_number"],
                name="content_idx_kind_page",
            ),
        ),
    ]
