# Generated by Django 6.0.2 on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_contentsearchentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="file",
            field=models.FileField(
                upload_to="videos",
                blank=True,
                help_text="Upload a video file for local playback (MP4/WebM/OGG).",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Optional video URL (YouTube/Vimeo). Leave blank if uploading a file.",
            ),
        ),
    ]
