# Generated by Django 6.0.2 on 2026-04-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_video_file_and_optional_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files", max_length=500),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.FileField(upload_to="images", max_length=500),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                upload_to="videos",
                blank=True,
                max_length=500,
                help_text="Upload a video file for local playback (MP4/WebM/OGG).",
            ),
        ),
    ]
