# Generated by ChatGPT for the notes feature migration.
from django.conf import settings  # Access the configured user model.
from django.db import migrations, models  # Migration base classes and field types.
import django.db.models.deletion  # Deletion behaviors for foreign keys.


# Initial schema migration for the notes app.
class Migration(migrations.Migration):
    # Declare this as the first migration for the app.
    initial = True

    # Define migration dependencies.
    dependencies = [
        # Depend on the swappable user model.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # Define the operations for this migration.
    operations = [
        # Create the Tag model table.
        migrations.CreateModel(
            name="Tag",  # Model name.
            fields=[
                # Primary key field.
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                # Tag display name.
                ("name", models.CharField(max_length=60)),
                # Tag slug for filtering.
                ("slug", models.SlugField(max_length=70)),
                # Tag created timestamp.
                ("created_at", models.DateTimeField(auto_now_add=True)),
                # Tag updated timestamp.
                ("updated_at", models.DateTimeField(auto_now=True)),
                # User relation for per-user tag ownership.
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="note_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                # Order tags alphabetically.
                "ordering": ["name"],
                # Enforce uniqueness per user/slug pair.
                "unique_together": {("user", "slug")},
            },
        ),
        # Create the Note model table.
        migrations.CreateModel(
            name="Note",  # Model name.
            fields=[
                # Primary key field.
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                # Note title.
                ("title", models.CharField(max_length=200)),
                # Note HTML content.
                ("content_html", models.TextField(blank=True, default="")),
                # Note created timestamp.
                ("created_at", models.DateTimeField(auto_now_add=True)),
                # Note updated timestamp.
                ("updated_at", models.DateTimeField(auto_now=True)),
                # Optional tag relation.
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes",
                        to="notes.tag",
                    ),
                ),
                # User relation for per-user note ownership.
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                # Order notes newest first.
                "ordering": ["-created_at"],
            },
        ),
    ]
