# Generated by Django 6.0.2 on 2026-03-14

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F, Func


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
        ("courses", "0005_coursesearchindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteSearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.TextField(blank=True, default="")),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "note",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_index",
                        to="notes.note",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="notesearchindex",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    Func(
                        F("document"),
                        function="immutable_unaccent",
                        output_field=models.TextField(),
                    ),
                    config="simple",
                ),
                name="note_idx_doc_tsv_gin",
            ),
        ),
        migrations.AddIndex(
            model_name="notesearchindex",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["document"],
                name="note_idx_doc_trgm_gin",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
