# Generated by ChatGPT for multi-tag notes migration.
from django.db import migrations, models


def copy_single_tag_to_many(apps, schema_editor):
    Note = apps.get_model("notes", "Note")
    db_alias = schema_editor.connection.alias
    for note in Note.objects.using(db_alias).exclude(tag_id__isnull=True).iterator():
        if note.tag_id:
            note.tags.add(note.tag_id)


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_notesearchindex"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="notes", to="notes.tag"),
        ),
        migrations.RunPython(copy_single_tag_to_many, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="note",
            name="tag",
        ),
    ]
