# Generated by Django 6.0.2 on 2026-04-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_multi_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_time_now',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
